backend:
  name: git-gateway
  branch: main
media_folder: "src/images/netlify"
public_folder: "/static/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/cms/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Minutes to read (approximate)", name: "minutes", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
    - name: "faqs"
      label: "FAQs" # Used in the UI
      folder: "/cms/faqs" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{fields.title}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields:
        - {label: "Two-word title of the question", name: "title", widget: "string"}
        - {label: "Order of Appearance(check for duplicates)", name: "order", widget: "number"}
        - {label: "Question", name: "question", widget: "text"}
        - {label: "Answer", name: "answer", widget: "text"}
