backend:
  name: git-gateway
  branch: main
media_folder: "src/images/netlify"
public_folder: "/static/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "/cms/blog"
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Minutes to read (approximate)", name: "minutes", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "faqs"
    label: "FAQs"
    folder: "/cms/faqs"
    create: true
    slug: "{{fields.title}}"
    fields:
      - {label: "Two-word title of the question", name: "title", widget: "string"}
      - {label: "Order of Appearance(check for duplicates)", name: "order", widget: "number"}
      - {label: "Question", name: "question", widget: "text"}
      - {label: "Answer", name: "answer", widget: "markdown"}
