---
new_page_extension: md
auto_deploy: false
admin_path: '/.forestry/'
webhook_url:
sections:
- type: document
  path: src/blog
  label: Blog
- type: document
  path: src/faqs
  label: FAQs
upload_dir: /src/images/blog
public_path: /src/images
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gatsby develop
